services:
  web:
    image: nginx:alpine
    ports:
      - "8181:80"
      - "443:443"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    container_name: zero-looper
    networks:
      - app_net

networks:
  app_net:
    name: zero-looper_app_net
    external: true
